# Generated by Django 5.0 on 2024-02-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='system',
            new_name='symptom',
        ),
    ]
