# Generated by Django 5.0 on 2024-02-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='sug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='speacialization',
            old_name='sug',
            new_name='slug',
        ),
    ]
